apiVersion: v1
kind: Pod
metadata:
  name: two-containers-pod
spec:
  volumes:
    - name: shared-data
      emptyDir: {}
  containers:
    - name: container1
      image: alpine:3.12.0
      command: ["sh", "-c", "tail -f /dev/null"]
      volumeMounts:
        - name: shared-data
          mountPath: /etc/a
    - name: container2
      image: alpine:3.12.0
      command: ["sh", "-c", "tail -f /dev/null"]
      volumeMounts:
        - name: shared-data
          mountPath: /etc/b
